name: Deploy to Github Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build nuxt generate and deploy to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # install
          npm ci
          # generate
          npm run generate
          # navigate into the build output directory
          cd dist
          # Git push to gh-pages
          git config --global init.defaultBranch main
          git init 
          git config --local user.email "${GITHUB_ACTOR}"
          git config --local user.name "${GITHUB_ACTOR}"
          git add -A
          git commit -m 'deploy'
          git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git main:gh-pages
